Repository pagopa/pagopa-checkout-fe, pull requests merged in 2024-09, with the labels that each got.

#367 [CHK-2957] feat: add links in the footer
  src/components/commons/Footer.tsx
  src/translations/en/translations.json
  src/translations/it/translations.json
Labels: minor

#372 fix: update readme for project initialization
  README.md
Labels: documentation

#370 [CJK-2430] adding dynamic informative label handlers
  src/routes/PaymentEmailPage.tsx
Labels: minor

#373 [CHK-3219] fix: button style on firefox inside response page
  src/routes/PaymentResponsePage.tsx
  src/routes/PaymentResponsePageV2.tsx
Labels: bug

#371 [CHK 2429] feat: continue label on cart flow
  src/routes/PaymentResponsePage.tsx
  src/routes/PaymentResponsePageV2.tsx
  src/translations/de/translations.json
  src/translations/en/translations.json
  src/translations/fr/translations.json
  src/translations/it/translations.json
  src/translations/sl/translations.json
Labels: minor

#386 [CHK-3244] fix: test openapi lang optional header
  package.json
  yarn.lock
Labels: bug

#385 [CHK-3226] fix: show language select until payment methods page
  src/components/commons/Footer.tsx
  src/translations/lang.ts
Labels: bug
