Repository pagopa/pagopa-checkout-fe, pull requests merged in 2025-04, with the labels that each got.

#486 [CHK-3982] Revert codecov
  .devops/pagopa-code-review-pipelines.yml
Labels: ignore-for-release

#459 feat: [PIDM-216] add new ToS page
  src/components/PrivacyPolicy/PrivacyInfo.tsx
  src/components/commons/Footer.tsx
  static/privacypolicy/it.html
  static/terms/it.html
  static/terms/style.css
Labels: minor

#492 [PIDM-416] fix(test) fix integration tests
  src/__integration_tests__/authentication.integration.test.ts
  src/__integration_tests__/paymentflow.integration.test.ts
  src/__integration_tests__/utils/helpers.js
Labels: ignore-for-release

#488 [CHK-3982] add coverage report
  .devops/pagopa-code-review-pipelines.yml
  .gitignore
  jest.config.js
  package.json
  sonar-project.properties
  yarn.lock
Labels: ignore-for-release

#480 chore(localization): [PIDM-382] update payment summary modal description
  src/routes/PaymentSummaryPage.tsx
  src/translations/de/translations.json
  src/translations/en/translations.json
  src/translations/fr/translations.json
  src/translations/it/translations.json
  src/translations/sl/translations.json
Labels: minor, skip-release, ignore-for-release

#495 [CHK-4023] feat: helper.js refactoring
  src/routes/CancelledPage.tsx
  src/routes/KOPage.tsx
  src/routes/PaymentCheckPage.tsx
  src/routes/PaymentResponsePage.tsx
  src/routes/PaymentResponsePageV2.tsx
  src/routes/SessionExpiredPage.tsx
  src/utils/__tests__/api/helpers/checkoutAuthServiceHelper.test.tsx
  src/utils/__tests__/api/helpers/checkoutFeatureFlagsHelper.test.ts
  src/utils/__tests__/api/helpers/ecommerce/ecommercePaymentMethodsHelper.test.ts
  src/utils/__tests__/api/helpers/ecommerce/ecommercePaymentRequestsHelper.test.ts
  src/utils/__tests__/api/helpers/ecommerce/ecommerceTransactionsHelper.test.ts
  src/utils/__tests__/api/helpers/recaptchaHelper.test.tsx
  src/utils/api/helper.ts
  src/utils/api/helpers/checkoutAuthServiceHelper.ts
  src/utils/api/helpers/checkoutFeatureFlagsHelper.ts
  src/utils/api/helpers/donationHelper.ts
  src/utils/api/helpers/ecommerce/ecommercePaymentMethodsHelper.ts
  src/utils/api/helpers/ecommerce/ecommercePaymentRequestsHelper.ts
  src/utils/api/helpers/ecommerce/ecommerceTransactionsHelper.ts
  src/utils/api/helpers/ecommerce/nodeFaultCode.ts
  src/utils/api/helpers/recaptchaHelper.ts
  src/utils/testUtils.ts
Labels: minor

#485 test: [CHK-3985] add utils unit tests
  .devops/pagopa-code-review-pipelines.yml
  jest.config.js
  sonar-project.properties
  src/components/commons/__tests__/LoginHeader.test.tsx
  src/routes/__tests__/AuthCallbackPage.test.tsx
  src/routes/__tests__/PaymentNoticePage.test.tsx
  src/utils/__tests__/BuildConfig.test.ts
  src/utils/__tests__/api/client.test.ts
  src/utils/__tests__/api/helpers/checkoutAuthServiceHelper.test.tsx
  src/utils/__tests__/api/helpers/checkoutFeatureFlagsHelper.test.ts
  src/utils/__tests__/api/helpers/ecommerce/ecommercePaymentMethodsHelper.test.ts
  src/utils/__tests__/api/helpers/ecommerce/ecommercePaymentRequestsHelper.test.ts
  src/utils/__tests__/api/helpers/ecommerce/ecommerceTransactionsHelper.test.ts
  src/utils/__tests__/api/response.test.ts
  src/utils/__tests__/api/transactionsErrorHelper.test.ts
  src/utils/__tests__/cart/cart.test.ts
  src/utils/__tests__/config/config.test.ts
  src/utils/__tests__/config/fetch.test.ts
  src/utils/__tests__/config/mixpanelHelperInit.test.ts
  src/utils/__tests__/counter.test.ts
  src/utils/__tests__/errors/checkErrorModal.test.ts
  src/utils/__tests__/errors/errorsModel.test.ts
  src/utils/__tests__/eventListeners.test.ts
  src/utils/__tests__/featureFlag.test.ts
  src/utils/__tests__/form/formatters.test.ts
  src/utils/__tests__/form/validators.test.ts
  src/utils/__tests__/regex/urlUtili.test.ts
  src/utils/__tests__/transactions/transactionHelper.test.ts
  src/utils/__tests__/transformers/paymentTrasformers.test.ts
  src/utils/__tests__/transformers/text.test.ts
  src/utils/__tests__/urlUtili.test.ts
  src/utils/sessionData/PaymentSession.ts
  src/utils/sessionData/WalletSession.ts
  src/utils/testing/testRenderProviders.tsx
  src/utils/testing/testUtils.ts
Labels: enhancement, minor, skip-release, ignore-for-release
